//-----------------------------------------------------------------------
// Copyright (c) 2014 Microsoft Corporation. All rights reserved.
// Use of this sample source code is subject to the terms of the Microsoft license 
// agreement under which you licensed this sample source code and is provided AS-IS.
// If you did not accept the terms of the license agreement, you are not authorized 
// to use this sample source code. For the terms of the license, please see the 
// license agreement between you and Microsoft.
//-----------------------------------------------------------------------

namespace Microsoft.Protocols.TestSuites.MS_OXORULE
{
    using System;
    using System.Collections.Generic;
    using Microsoft.Protocols.TestSuites.Common;

    /// <summary>
    /// Action Data buffer format for ActionType: OP_REPLY, OP_OOF_REPLY
    /// </summary>
    public class ReplyActionDataOfExtendedRule : IActionData
    {
        /// <summary>
        /// An integer that specifies the size, in bytes, of the ReplyTemplateMessageEID field.
        /// </summary>
        private uint messageEIDSize;

        /// <summary>
        /// A Message EntryID structure, as specified in [MS-OXCDATA] section 2.2.4.2, that contains the entry ID of the reply template.
        /// </summary>
        private byte[] replyTemplateMessageEID;

        /// <summary>
        /// The ReplyTemplateGUID field in the Reply ActionData buffer is the value of the GUID generated by the client in the process of creating a Reply template
        /// </summary>
        private byte[] replyTemplateGUID;

        /// <summary>
        /// Gets or sets an integer that specifies the size, in bytes, of the ReplyTemplateMessageEID field.ReplyTemplate FID which obtained from a Message Template
        /// </summary>
        public uint MessageEIDSize
        {
            get { return this.messageEIDSize; }
            set { this.messageEIDSize = value; }
        }

        /// <summary>
        /// Gets or sets a Message EntryID structure, as specified in [MS-OXCDATA] section 2.2.4.2, that contains the entry ID of the reply template.
        /// </summary>
        public byte[] ReplyTemplateMessageEID
        {
            get { return this.replyTemplateMessageEID; }
            set { this.replyTemplateMessageEID = value; }
        }

        /// <summary>
        /// Gets or sets the ReplyTemplateGUID
        /// </summary>
        public byte[] ReplyTemplateGUID
        {
            get { return this.replyTemplateGUID; }
            set { this.replyTemplateGUID = value; }
        }

        /// <summary>
        /// The total Size of this ActionData buffer
        /// </summary>
        /// <returns>Number of bytes in this ActionData buffer.</returns>
        public int Size()
        {
            return this.Serialize().Length;
        }

        /// <summary>
        /// Get serialized byte array for this ActionData
        /// </summary>
        /// <returns>Serialized byte array.</returns>
        public byte[] Serialize()
        {
            List<byte> result = new List<byte>();
            result.AddRange(BitConverter.GetBytes(this.MessageEIDSize));
            result.AddRange(this.ReplyTemplateMessageEID);
            result.AddRange(this.ReplyTemplateGUID);

            return result.ToArray();
        }

        /// <summary>
        /// Deserialized byte array to a ReplyActionData instance
        /// </summary>
        /// <param name="buffer">Byte array contains data of an ActionData instance.</param>
        /// <returns>Bytes count that deserialized in buffer.</returns>
        public uint Deserialize(byte[] buffer)
        {
            BufferReader bufferReader = new BufferReader(buffer);
            this.messageEIDSize = bufferReader.ReadUInt32();
            this.replyTemplateMessageEID = bufferReader.ReadBytes(this.messageEIDSize);
            uint guidLength = (uint)Guid.NewGuid().ToByteArray().Length;
            this.ReplyTemplateGUID = bufferReader.ReadBytes((uint)guidLength);

            return bufferReader.Position;
        }
    }
}