//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Protocols.TestSuites.MS_OXCTABL {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Reflection;
    using Microsoft.SpecExplorer.Runtime.Testing;
    using Microsoft.Protocols.TestTools;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Spec Explorer", "3.5.3130.0")]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite : PtfTestClassBase {
        
        public S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite() {
            this.SetSwitch("ProceedControlTimeout", "100");
            this.SetSwitch("QuiescenceTimeout", "2000000");
        }
        
        #region Expect Delegates
        public delegate void CheckMAPIHTTPTransportSupportedDelegate1(bool isSupported);
        
        public delegate void CheckRequirementEnabledDelegate1(bool enabled);
        
        public delegate void RopExpandRowResponseDelegate1(bool isLastSetColumnData);
        #endregion
        
        #region Event Metadata
        static System.Reflection.MethodBase CheckMAPIHTTPTransportSupportedInfo = TestManagerHelpers.GetMethodInfo(typeof(Microsoft.Protocols.TestSuites.MS_OXCTABL.IMS_OXCTABLAdapter), "CheckMAPIHTTPTransportSupported", typeof(bool).MakeByRefType());
        
        static System.Reflection.MethodBase CheckRequirementEnabledInfo = TestManagerHelpers.GetMethodInfo(typeof(Microsoft.Protocols.TestSuites.MS_OXCTABL.IMS_OXCTABLAdapter), "CheckRequirementEnabled", typeof(int), typeof(bool).MakeByRefType());
        
        static System.Reflection.EventInfo RopExpandRowResponseInfo = TestManagerHelpers.GetEventInfo(typeof(Microsoft.Protocols.TestSuites.MS_OXCTABL.IMS_OXCTABLAdapter), "RopExpandRowResponse");
        #endregion
        
        #region Adapter Instances
        private Microsoft.Protocols.TestSuites.MS_OXCTABL.IMS_OXCTABLAdapter IMS_OXCTABLAdapterInstance;
        #endregion
        
        #region Class Initialization and Cleanup
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void ClassInitialize(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext context) {
            PtfTestClassBase.Initialize(context);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void ClassCleanup() {
            PtfTestClassBase.Cleanup();
        }
        #endregion
        
        #region Test Initialization and Cleanup
        protected override void TestInitialize() {
            this.InitializeTestManager();
            this.IMS_OXCTABLAdapterInstance = ((Microsoft.Protocols.TestSuites.MS_OXCTABL.IMS_OXCTABLAdapter)(this.Manager.GetAdapter(typeof(Microsoft.Protocols.TestSuites.MS_OXCTABL.IMS_OXCTABLAdapter))));
            this.Manager.Subscribe(RopExpandRowResponseInfo, this.IMS_OXCTABLAdapterInstance);
        }
        
        protected override void TestCleanup() {
            base.TestCleanup();
            this.CleanupTestManager();
        }
        #endregion
        
        #region Test Starting in S0
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite() {
            this.Manager.BeginTest("MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite");
            this.Manager.Comment("reaching state \'S0\'");
            bool temp0;
            this.Manager.Comment("executing step \'call CheckMAPIHTTPTransportSupported(out _)\'");
            this.IMS_OXCTABLAdapterInstance.CheckMAPIHTTPTransportSupported(out temp0);
            this.Manager.AddReturn(CheckMAPIHTTPTransportSupportedInfo, null, temp0);
            this.Manager.Comment("reaching state \'S1\'");
            int temp5 = this.Manager.ExpectReturn(this.QuiescenceTimeout, true, new ExpectedReturn(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.CheckMAPIHTTPTransportSupportedInfo, null, new CheckMAPIHTTPTransportSupportedDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuiteCheckMAPIHTTPTransportSupportedChecker)), new ExpectedReturn(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.CheckMAPIHTTPTransportSupportedInfo, null, new CheckMAPIHTTPTransportSupportedDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuiteCheckMAPIHTTPTransportSupportedChecker1)));
            if ((temp5 == 0)) {
                this.Manager.Comment("reaching state \'S8\'");
                goto label1;
            }
            if ((temp5 == 1)) {
                this.Manager.Comment("reaching state \'S9\'");
                this.Manager.Comment("executing step \'call InitializeTable(INVALID_TABLE)\'");
                this.IMS_OXCTABLAdapterInstance.InitializeTable(Microsoft.Protocols.TestSuites.MS_OXCTABL.TableType.INVALID_TABLE);
                this.Manager.Comment("reaching state \'S16\'");
                this.Manager.Comment("checking step \'return InitializeTable\'");
                this.Manager.Comment("reaching state \'S20\'");
                bool temp1;
                this.Manager.Comment("executing step \'call CheckRequirementEnabled(748,out _)\'");
                this.IMS_OXCTABLAdapterInstance.CheckRequirementEnabled(748, out temp1);
                this.Manager.AddReturn(CheckRequirementEnabledInfo, null, temp1);
                this.Manager.Comment("reaching state \'S24\'");
                int temp4 = this.Manager.ExpectReturn(this.QuiescenceTimeout, true, new ExpectedReturn(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.CheckRequirementEnabledInfo, null, new CheckRequirementEnabledDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuiteCheckRequirementEnabledChecker)), new ExpectedReturn(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.CheckRequirementEnabledInfo, null, new CheckRequirementEnabledDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuiteCheckRequirementEnabledChecker1)));
                if ((temp4 == 0)) {
                    this.Manager.Comment("reaching state \'S28\'");
                    Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues temp2;
                    this.Manager.Comment("executing step \'call RopExpandRow(False,False,False)\'");
                    temp2 = this.IMS_OXCTABLAdapterInstance.RopExpandRow(false, false, false);
                    this.Manager.Checkpoint("MS-OXCTABL_R274");
                    this.Manager.Comment("reaching state \'S34\'");
                    this.Manager.Comment("checking step \'return RopExpandRow/ecNotSupported\'");
                    TestManagerHelpers.AssertAreEqual<Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues>(this.Manager, Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues.ecNotSupported, temp2, "return of RopExpandRow, state S34");
                    this.Manager.Comment("reaching state \'S38\'");
                    if ((this.Manager.ExpectEvent(this.QuiescenceTimeout, true, new ExpectedEvent(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.RopExpandRowResponseInfo, null, new RopExpandRowResponseDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuiteRopExpandRowResponseChecker))) != -1)) {
                        this.Manager.Comment("reaching state \'S42\'");
                    }
                    else {
                        this.Manager.CheckObservationTimeout(false, new ExpectedEvent(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.RopExpandRowResponseInfo, null, new RopExpandRowResponseDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuiteRopExpandRowResponseChecker)));
                    }
                    goto label0;
                }
                if ((temp4 == 1)) {
                    this.Manager.Comment("reaching state \'S29\'");
                    Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues temp3;
                    this.Manager.Comment("executing step \'call RopExpandRow(False,False,False)\'");
                    temp3 = this.IMS_OXCTABLAdapterInstance.RopExpandRow(false, false, false);
                    this.Manager.Checkpoint("MS-OXCTABL_R274");
                    this.Manager.Comment("reaching state \'S35\'");
                    this.Manager.Comment("checking step \'return RopExpandRow/ecNotSupported\'");
                    TestManagerHelpers.AssertAreEqual<Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues>(this.Manager, Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues.ecNotSupported, temp3, "return of RopExpandRow, state S35");
                    this.Manager.Comment("reaching state \'S39\'");
                    if ((this.Manager.ExpectEvent(this.QuiescenceTimeout, true, new ExpectedEvent(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.RopExpandRowResponseInfo, null, new RopExpandRowResponseDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuiteRopExpandRowResponseChecker1))) != -1)) {
                        this.Manager.Comment("reaching state \'S43\'");
                    }
                    else {
                        this.Manager.CheckObservationTimeout(false, new ExpectedEvent(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.RopExpandRowResponseInfo, null, new RopExpandRowResponseDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuiteRopExpandRowResponseChecker1)));
                    }
                    goto label0;
                }
                throw new InvalidOperationException("never reached");
            label0:
;
                goto label1;
            }
            throw new InvalidOperationException("never reached");
        label1:
;
            this.Manager.EndTest();
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuiteCheckMAPIHTTPTransportSupportedChecker(bool isSupported) {
            this.Manager.Comment("checking step \'return CheckMAPIHTTPTransportSupported/[out False]\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, false, isSupported, "isSupported of CheckMAPIHTTPTransportSupported, state S1");
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuiteCheckMAPIHTTPTransportSupportedChecker1(bool isSupported) {
            this.Manager.Comment("checking step \'return CheckMAPIHTTPTransportSupported/[out True]\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, true, isSupported, "isSupported of CheckMAPIHTTPTransportSupported, state S1");
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuiteCheckRequirementEnabledChecker(bool enabled) {
            this.Manager.Comment("checking step \'return CheckRequirementEnabled/[out True]\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, true, enabled, "enabled of CheckRequirementEnabled, state S24");
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuiteRopExpandRowResponseChecker(bool isLastSetColumnData) {
            this.Manager.Comment("checking step \'event RopExpandRowResponse(False)\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, false, isLastSetColumnData, "isLastSetColumnData of RopExpandRowResponse, state S38");
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuiteCheckRequirementEnabledChecker1(bool enabled) {
            this.Manager.Comment("checking step \'return CheckRequirementEnabled/[out False]\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, false, enabled, "enabled of CheckRequirementEnabled, state S24");
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuiteRopExpandRowResponseChecker1(bool isLastSetColumnData) {
            this.Manager.Comment("checking step \'event RopExpandRowResponse(False)\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, false, isLastSetColumnData, "isLastSetColumnData of RopExpandRowResponse, state S39");
        }
        #endregion
        
        #region Test Starting in S2
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite1() {
            this.Manager.BeginTest("MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite1");
            this.Manager.Comment("reaching state \'S2\'");
            bool temp6;
            this.Manager.Comment("executing step \'call CheckMAPIHTTPTransportSupported(out _)\'");
            this.IMS_OXCTABLAdapterInstance.CheckMAPIHTTPTransportSupported(out temp6);
            this.Manager.AddReturn(CheckMAPIHTTPTransportSupportedInfo, null, temp6);
            this.Manager.Comment("reaching state \'S3\'");
            int temp8 = this.Manager.ExpectReturn(this.QuiescenceTimeout, true, new ExpectedReturn(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.CheckMAPIHTTPTransportSupportedInfo, null, new CheckMAPIHTTPTransportSupportedDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite1CheckMAPIHTTPTransportSupportedChecker)), new ExpectedReturn(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.CheckMAPIHTTPTransportSupportedInfo, null, new CheckMAPIHTTPTransportSupportedDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite1CheckMAPIHTTPTransportSupportedChecker1)));
            if ((temp8 == 0)) {
                this.Manager.Comment("reaching state \'S10\'");
                this.Manager.Comment("executing step \'call InitializeTable(ATTACHMENTS_TABLE)\'");
                this.IMS_OXCTABLAdapterInstance.InitializeTable(Microsoft.Protocols.TestSuites.MS_OXCTABL.TableType.ATTACHMENTS_TABLE);
                this.Manager.Comment("reaching state \'S17\'");
                this.Manager.Comment("checking step \'return InitializeTable\'");
                this.Manager.Comment("reaching state \'S21\'");
                Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues temp7;
                this.Manager.Comment("executing step \'call RopCollapseRow(False,False)\'");
                temp7 = this.IMS_OXCTABLAdapterInstance.RopCollapseRow(false, false);
                this.Manager.Checkpoint("MS-OXCTABL_R578");
                this.Manager.Comment("reaching state \'S25\'");
                this.Manager.Comment("checking step \'return RopCollapseRow/ecNotSupported\'");
                TestManagerHelpers.AssertAreEqual<Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues>(this.Manager, Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues.ecNotSupported, temp7, "return of RopCollapseRow, state S25");
                this.Manager.Comment("reaching state \'S30\'");
                goto label2;
            }
            if ((temp8 == 1)) {
                this.Manager.Comment("reaching state \'S11\'");
                goto label2;
            }
            throw new InvalidOperationException("never reached");
        label2:
;
            this.Manager.EndTest();
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite1CheckMAPIHTTPTransportSupportedChecker(bool isSupported) {
            this.Manager.Comment("checking step \'return CheckMAPIHTTPTransportSupported/[out True]\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, true, isSupported, "isSupported of CheckMAPIHTTPTransportSupported, state S3");
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite1CheckMAPIHTTPTransportSupportedChecker1(bool isSupported) {
            this.Manager.Comment("checking step \'return CheckMAPIHTTPTransportSupported/[out False]\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, false, isSupported, "isSupported of CheckMAPIHTTPTransportSupported, state S3");
        }
        #endregion
        
        #region Test Starting in S4
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite2() {
            this.Manager.BeginTest("MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite2");
            this.Manager.Comment("reaching state \'S4\'");
            bool temp9;
            this.Manager.Comment("executing step \'call CheckMAPIHTTPTransportSupported(out _)\'");
            this.IMS_OXCTABLAdapterInstance.CheckMAPIHTTPTransportSupported(out temp9);
            this.Manager.AddReturn(CheckMAPIHTTPTransportSupportedInfo, null, temp9);
            this.Manager.Comment("reaching state \'S5\'");
            int temp11 = this.Manager.ExpectReturn(this.QuiescenceTimeout, true, new ExpectedReturn(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.CheckMAPIHTTPTransportSupportedInfo, null, new CheckMAPIHTTPTransportSupportedDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite2CheckMAPIHTTPTransportSupportedChecker)), new ExpectedReturn(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.CheckMAPIHTTPTransportSupportedInfo, null, new CheckMAPIHTTPTransportSupportedDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite2CheckMAPIHTTPTransportSupportedChecker1)));
            if ((temp11 == 0)) {
                this.Manager.Comment("reaching state \'S12\'");
                this.Manager.Comment("executing step \'call InitializeTable(INVALID_TABLE)\'");
                this.IMS_OXCTABLAdapterInstance.InitializeTable(Microsoft.Protocols.TestSuites.MS_OXCTABL.TableType.INVALID_TABLE);
                this.Manager.Comment("reaching state \'S18\'");
                this.Manager.Comment("checking step \'return InitializeTable\'");
                this.Manager.Comment("reaching state \'S22\'");
                Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues temp10;
                this.Manager.Comment("executing step \'call RopCollapseRow(False,False)\'");
                temp10 = this.IMS_OXCTABLAdapterInstance.RopCollapseRow(false, false);
                this.Manager.Checkpoint("MS-OXCTABL_R284");
                this.Manager.Comment("reaching state \'S26\'");
                this.Manager.Comment("checking step \'return RopCollapseRow/ecNotSupported\'");
                TestManagerHelpers.AssertAreEqual<Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues>(this.Manager, Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues.ecNotSupported, temp10, "return of RopCollapseRow, state S26");
                this.Manager.Comment("reaching state \'S31\'");
                goto label3;
            }
            if ((temp11 == 1)) {
                this.Manager.Comment("reaching state \'S13\'");
                goto label3;
            }
            throw new InvalidOperationException("never reached");
        label3:
;
            this.Manager.EndTest();
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite2CheckMAPIHTTPTransportSupportedChecker(bool isSupported) {
            this.Manager.Comment("checking step \'return CheckMAPIHTTPTransportSupported/[out True]\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, true, isSupported, "isSupported of CheckMAPIHTTPTransportSupported, state S5");
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite2CheckMAPIHTTPTransportSupportedChecker1(bool isSupported) {
            this.Manager.Comment("checking step \'return CheckMAPIHTTPTransportSupported/[out False]\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, false, isSupported, "isSupported of CheckMAPIHTTPTransportSupported, state S5");
        }
        #endregion
        
        #region Test Starting in S6
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3() {
            this.Manager.BeginTest("MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3");
            this.Manager.Comment("reaching state \'S6\'");
            bool temp12;
            this.Manager.Comment("executing step \'call CheckMAPIHTTPTransportSupported(out _)\'");
            this.IMS_OXCTABLAdapterInstance.CheckMAPIHTTPTransportSupported(out temp12);
            this.Manager.AddReturn(CheckMAPIHTTPTransportSupportedInfo, null, temp12);
            this.Manager.Comment("reaching state \'S7\'");
            int temp17 = this.Manager.ExpectReturn(this.QuiescenceTimeout, true, new ExpectedReturn(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.CheckMAPIHTTPTransportSupportedInfo, null, new CheckMAPIHTTPTransportSupportedDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3CheckMAPIHTTPTransportSupportedChecker)), new ExpectedReturn(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.CheckMAPIHTTPTransportSupportedInfo, null, new CheckMAPIHTTPTransportSupportedDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3CheckMAPIHTTPTransportSupportedChecker1)));
            if ((temp17 == 0)) {
                this.Manager.Comment("reaching state \'S14\'");
                this.Manager.Comment("executing step \'call InitializeTable(ATTACHMENTS_TABLE)\'");
                this.IMS_OXCTABLAdapterInstance.InitializeTable(Microsoft.Protocols.TestSuites.MS_OXCTABL.TableType.ATTACHMENTS_TABLE);
                this.Manager.Comment("reaching state \'S19\'");
                this.Manager.Comment("checking step \'return InitializeTable\'");
                this.Manager.Comment("reaching state \'S23\'");
                bool temp13;
                this.Manager.Comment("executing step \'call CheckRequirementEnabled(748,out _)\'");
                this.IMS_OXCTABLAdapterInstance.CheckRequirementEnabled(748, out temp13);
                this.Manager.AddReturn(CheckRequirementEnabledInfo, null, temp13);
                this.Manager.Comment("reaching state \'S27\'");
                int temp16 = this.Manager.ExpectReturn(this.QuiescenceTimeout, true, new ExpectedReturn(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.CheckRequirementEnabledInfo, null, new CheckRequirementEnabledDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3CheckRequirementEnabledChecker)), new ExpectedReturn(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.CheckRequirementEnabledInfo, null, new CheckRequirementEnabledDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3CheckRequirementEnabledChecker1)));
                if ((temp16 == 0)) {
                    this.Manager.Comment("reaching state \'S32\'");
                    Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues temp14;
                    this.Manager.Comment("executing step \'call RopExpandRow(False,False,False)\'");
                    temp14 = this.IMS_OXCTABLAdapterInstance.RopExpandRow(false, false, false);
                    this.Manager.Checkpoint("MS-OXCTABL_R572");
                    this.Manager.Comment("reaching state \'S36\'");
                    this.Manager.Comment("checking step \'return RopExpandRow/ecNotSupported\'");
                    TestManagerHelpers.AssertAreEqual<Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues>(this.Manager, Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues.ecNotSupported, temp14, "return of RopExpandRow, state S36");
                    this.Manager.Comment("reaching state \'S40\'");
                    if ((this.Manager.ExpectEvent(this.QuiescenceTimeout, true, new ExpectedEvent(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.RopExpandRowResponseInfo, null, new RopExpandRowResponseDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3RopExpandRowResponseChecker))) != -1)) {
                        this.Manager.Comment("reaching state \'S44\'");
                    }
                    else {
                        this.Manager.CheckObservationTimeout(false, new ExpectedEvent(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.RopExpandRowResponseInfo, null, new RopExpandRowResponseDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3RopExpandRowResponseChecker)));
                    }
                    goto label4;
                }
                if ((temp16 == 1)) {
                    this.Manager.Comment("reaching state \'S33\'");
                    Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues temp15;
                    this.Manager.Comment("executing step \'call RopExpandRow(False,False,False)\'");
                    temp15 = this.IMS_OXCTABLAdapterInstance.RopExpandRow(false, false, false);
                    this.Manager.Checkpoint("MS-OXCTABL_R572");
                    this.Manager.Comment("reaching state \'S37\'");
                    this.Manager.Comment("checking step \'return RopExpandRow/ecNotSupported\'");
                    TestManagerHelpers.AssertAreEqual<Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues>(this.Manager, Microsoft.Protocols.TestSuites.MS_OXCTABL.TableRopReturnValues.ecNotSupported, temp15, "return of RopExpandRow, state S37");
                    this.Manager.Comment("reaching state \'S41\'");
                    if ((this.Manager.ExpectEvent(this.QuiescenceTimeout, true, new ExpectedEvent(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.RopExpandRowResponseInfo, null, new RopExpandRowResponseDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3RopExpandRowResponseChecker1))) != -1)) {
                        this.Manager.Comment("reaching state \'S45\'");
                    }
                    else {
                        this.Manager.CheckObservationTimeout(false, new ExpectedEvent(S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite.RopExpandRowResponseInfo, null, new RopExpandRowResponseDelegate1(this.MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3RopExpandRowResponseChecker1)));
                    }
                    goto label4;
                }
                throw new InvalidOperationException("never reached");
            label4:
;
                goto label5;
            }
            if ((temp17 == 1)) {
                this.Manager.Comment("reaching state \'S15\'");
                goto label5;
            }
            throw new InvalidOperationException("never reached");
        label5:
;
            this.Manager.EndTest();
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3CheckMAPIHTTPTransportSupportedChecker(bool isSupported) {
            this.Manager.Comment("checking step \'return CheckMAPIHTTPTransportSupported/[out True]\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, true, isSupported, "isSupported of CheckMAPIHTTPTransportSupported, state S7");
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3CheckRequirementEnabledChecker(bool enabled) {
            this.Manager.Comment("checking step \'return CheckRequirementEnabled/[out True]\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, true, enabled, "enabled of CheckRequirementEnabled, state S27");
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3RopExpandRowResponseChecker(bool isLastSetColumnData) {
            this.Manager.Comment("checking step \'event RopExpandRowResponse(False)\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, false, isLastSetColumnData, "isLastSetColumnData of RopExpandRowResponse, state S40");
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3CheckRequirementEnabledChecker1(bool enabled) {
            this.Manager.Comment("checking step \'return CheckRequirementEnabled/[out False]\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, false, enabled, "enabled of CheckRequirementEnabled, state S27");
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3RopExpandRowResponseChecker1(bool isLastSetColumnData) {
            this.Manager.Comment("checking step \'event RopExpandRowResponse(False)\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, false, isLastSetColumnData, "isLastSetColumnData of RopExpandRowResponse, state S41");
        }
        
        private void MSOXCTABL_S04_ExpandRowRops_CollapseorExpandRowNotSupported_TestSuite3CheckMAPIHTTPTransportSupportedChecker1(bool isSupported) {
            this.Manager.Comment("checking step \'return CheckMAPIHTTPTransportSupported/[out False]\'");
            TestManagerHelpers.AssertAreEqual<bool>(this.Manager, false, isSupported, "isSupported of CheckMAPIHTTPTransportSupported, state S7");
        }
        #endregion
    }
}
